name: Build & Deploy releases

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # macOS Catalina 10.15, Ubuntu 18.04, Windows Server 2019
        # see https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Prepare
        working-directory: build
        shell: cmd
        if: contains( matrix.os, 'windows')
        run: |
          curl -vLo qt-unified-windows-x86-online.exe http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
          qt-unified-windows-x86-online.exe --verbose --script ..\ci\qt.qs
      
      - name: Install Qt5 (mac)
        # Version 5.12.6
        # see https://github.com/marketplace/actions/install-qt
        uses: jurplel/install-qt-action@v2
        if: contains( matrix.os, 'macos')

      - name: Install Qt5 (ubuntu)
        # Version 5.12.6
        # see https://github.com/marketplace/actions/install-qt
        uses: jurplel/install-qt-action@v2
        if: contains( matrix.os, 'ubuntu')


      - name: Run CMake
        # see https://github.com/marketplace/actions/run-cmake
        uses: lukka/run-cmake@v0
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: '-G "Visual Studio 16 2019"'
          cmakeBuildType: "Release"
          buildDirectory: "${{ github.workspace }}/build"
