name: Build & Deploy releases

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # macOS Catalina 10.15, Ubuntu 18.04, Windows Server 2019
        # see https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Install Qt5
        # Version 5.12.6
        # see https://github.com/marketplace/actions/install-qt-dev-action
        uses: actions/install-qt-action@v0.1.1
        with:
          packages: 'qt.qt5.5126.gcc_64'

      - name: Run CMake
        # see https://github.com/marketplace/actions/run-cmake
        uses: lukka/run-cmake@v0
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeBuildType: "Release"
          buildDirectory: "${{ github.workspace }}/build"
